### PR TITLE
Fix blocking token refresh while animations are running

### PR DESCRIPTION
**Pull request by melvynhills**
## Summary of change
Use `setImmediate` to trigger unlocking callbacks instead of `InteractionManager.runAfterInteractions()` which can be paused for as long as any interactive animation is running.

## Related issues
https://github.com/supertokens/supertokens-react-native/issues/106

## Test Plan
n/a

## Documentation changes
n/a

## Checklist for important updates
- [x] Changelog has been updated
- [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
   - Along with the associated array in `lib/ts/version.ts`
- [x] Changes to the version if needed
   - In `package.json`
   - In `package-lock.json`
   - In `lib/ts/version.ts`
- [x] Had run `npm run build-pretty`
- [x] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
n/a

### CODE REVIEW

**Review by nkshah2 — APPROVED** [review]

**Comment by nkshah2** [comment]
Hey @melvynhills 

The PR looks good, just a heads up I made a tiny change to your branch to make the tests a little less unreliable. We'll get this merged sometime this week

**Comment by rishabhpoddar** [comment]
We have also added your profile to the supertokens-core readme :)

**Comment by melvynhills** [comment]
Yeah I didn't take the time to try to run the tests nor patch my local `node_modules` yet, so I guess it needs some testing before production release?
Thanks guys!

**Comment by rishabhpoddar** [comment]
Yea, we did run tests on our CICD already. And have released it.

**Pull request merged**
